using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using System.Data.Entity;

namespace Sales_Manement_System.PL
{
    public partial class FormCategory : Form
    {
        public FormCategory()
        {
            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            Sales_Manement_System.DatabaseSMPEntities dbContext = new Sales_Manement_System.DatabaseSMPEntities();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TableCategories.LoadAsync().ContinueWith(loadTask =>
            {
    // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TableCategories.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }
    }
}
